ITO-27 : Users are not able to upload new pictures taken when a work order note is created
ubreakifix/webcam-directive pull request #2
Opened 2022-02-11 16:58 UTC by dmccrae-ubif

2022-02-11 17:03 UTC, dmccrae-ubif commented on app/scripts/webcam.js
> +          alert('yea buddy');
```suggestion

```

2022-02-11 18:43 UTC, alcantaraj approved these changes
were you able to test this with a mobile device? I believe the expectation would be for the phone to default to the back cam. I believe there was even a different behavior between iphone v android and browsers. If that feature isn't really a business priority anymore, that's cool too.

2022-02-11 19:41 UTC, dmccrae-ubif commented
> were you able to test this with a mobile device? I believe the expectation would be for the phone to default to the back cam. I believe there was even a different behavior between iphone v android and browsers. If that feature isn't really a business priority anymore, that's cool too.

Was able to test this on my iphone, prod portal was not using my back camera.

2022-02-11 19:59 UTC, alcantaraj commented
> > were you able to test this with a mobile device? I believe the expectation would be for the phone to default to the back cam. I believe there was even a different behavior between iphone v android and browsers. If that feature isn't really a business priority anymore, that's cool too.
> 
> Was able to test this on my iphone, prod portal was not using my back camera. Mobile test was on safari.

@dave9011 does that functionality still matter? is it a dealbreaker?

2022-05-17 17:41 UTC, alcantaraj approved these changes

2022-06-17 07:12 UTC, dave9011 approved these changes

2022-06-17 07:12 UTC, dave9011 commented on app/scripts/webcam.js
> + * @version: 3.2.2
We might just want to remove this line to avoid confusion since the only place that really matters is the package.json file anyways

```suggestion
 * @version: 3.3.1
```

2022-06-17 07:16 UTC, dave9011 requested changes

2022-06-17 07:16 UTC, dave9011 commented on app/scripts/webcam.js
> + * @version: 3.2.2
I forgot I had mentioned updating the README file to remove some outdated info. Can we update it to remove the following 3 things:

note: maybe for the installation example we just update the path to the script instead of removing it
![image](https://user-images.githubusercontent.com/1569157/174245884-3859cece-7cc4-4104-a333-20245fc9eb88.png)

2022-06-17 17:02 UTC, dave9011 commented on app/scripts/webcam.js
> + * @version: 3.2.2
Can you remove this line?

2022-06-17 17:07 UTC, dave9011 approved these changes

2022-06-17 17:18 UTC, merged