Add NPM publish github action
ubreakifix/webcam-directive pull request #3
Opened 2022-06-06 16:10 UTC by dmccrae-ubif

2022-06-06 16:10 UTC, dmccrae-ubif commented on .github/workflows/npm-publish.yml
> +      - ITO-230
```suggestion
      - master
```

2022-06-06 16:42 UTC, dave9011 approved these changes

2022-06-06 16:53 UTC, dave9011 requested changes
Let's update the README file with updated installation instructions

2022-06-08 15:03 UTC, dave9011 requested changes

2022-06-08 15:27 UTC, dmccrae-ubif commented on README.md
> +npm install @ubreakifix/webcam@3.2.13
can exclude the version as it then goes off package.json

2022-06-08 15:27 UTC, dmccrae-ubif commented on README.md
> +npm install @ubreakifix/webcam@3.2.13
```suggestion
npm install @ubreakifix/webcam
```

2022-06-08 15:49 UTC, merged